# Generated by Django 4.1.5 on 2023-01-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
    ]
