# Generated by Django 4.1.5 on 2023-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_year_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dsdhh', upload_to='pics'),
            preserve_default=False,
        ),
    ]
